stages:
  - build
  - deploy

compile:
    stage: build
    script:
      - cd search
      - mvn package -B >> runtime.log
      - cd ..
    only:
      - master

deploy:
    stage: deploy
    script:
      cd search
      - ./start.sh
      cd ..
    only:
      - master
