image: maven:3-jdk-8
stages:
  - deploy

deploy:
  stage: deploy
  script:
    - cd search
    - pwd
    - mvn package -B
    - nohup sh run.sh SearchApplication > SearchApplication.log &
    - cd ..
    - pwd
  only:
    - master
